Chat window implemented
linhapeter/react-start pull request #4
Opened 2023-10-22 17:44 UTC by linhapeter

2023-10-22 21:06 UTC, volkov-a-dev requested changes

2023-10-22 21:06 UTC, volkov-a-dev commented on src/messenger/Chat.jsx
> +          <Message key={index} text={message.text} />
Using an index on a given key is bad practice. Please read the [docs](https://react.dev/learn/rendering-lists#rules-of-keys)

2023-10-22 21:06 UTC, volkov-a-dev commented on src/messenger/Chat.jsx
> +      console.log(messages);
Please remove/comment out the console log

2023-10-22 21:06 UTC, volkov-a-dev commented on src/messenger/Chat.jsx
> +    console.log(messageInput);
Please remove/comment out the console log

2023-10-22 21:06 UTC, volkov-a-dev commented on src/messenger/Chat.jsx
> +      <input className="input-message" type="text" onChange={changeInputMessage} onKeyPress={sendMessageOnEnter} />
Why is CSS used? Why is the file here?

2023-10-22 21:06 UTC, volkov-a-dev commented on src/messenger/Chat.jsx
Why is business logic not separated from rendering?

2023-10-22 21:06 UTC, volkov-a-dev commented on src/messenger/Chat.jsx
Do you have an eslint error in this file?

2023-10-22 21:06 UTC, volkov-a-dev commented on src/App.jsx
> +import "./style.css";
Why is there CSS here?

2023-10-23 16:40 UTC, linhapeter commented on src/App.jsx
> +import "./style.css";
I'don't understand where should be css?

2023-10-23 19:01 UTC, volkov-a-dev commented on src/App.jsx
> +import "./style.css";
I expressed myself incorrectly. This style.css file must have global styles.
Styles intended for a component must be at the component level.

2023-10-23 19:02 UTC, merged