Routes created and added style to navigation
linhapeter/react-start pull request #6
Opened 2023-10-30 13:31 UTC by linhapeter

2023-10-31 08:39 UTC, volkov-a-dev requested changes

2023-10-31 08:39 UTC, volkov-a-dev commented on src/style/header.css
Why not connect scss?

2023-10-31 08:39 UTC, volkov-a-dev commented on src/style/chat.css
Why not connect scss?

2023-10-31 08:39 UTC, volkov-a-dev commented on src/pages/home/Home.jsx
If the component should return only JSX, without any manipulations with props, store, or local state. You can shorten this code to:
```
import React from "react";
const Home = () => (
    <div>
        <h1>Home</h1>
    </div>
);

export default Home;
```

2023-10-31 08:39 UTC, volkov-a-dev commented on src/pages/examples/form/ResponseContent.jsx
> +ResponseContent.propTypes = {
https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/require-default-props.md
propType " response" is not required, but has no corresponding defaultProps declaration.

ResponseContent.propTypes = {
  response: PropTypes.shape({
    json: PropTypes.shape({
      name: PropTypes.string,
      password: PropTypes.string,
    }),
  }),
};

ResponseContent.defaultProps = {
  response: {
     json: {
       name: '',
       password: ''
     }
  }
}

2023-10-31 08:39 UTC, volkov-a-dev commented on src/header/Header.jsx
> +      <Routes>
https://reactrouter.com/en/main/router-components/browser-router
You need to move the routing to a separate folder and make it more isolated. Also, why not write a loop that would go through the array and return the same thing as here?
Advice: If it is possible to automate a process, automate it

2023-10-31 08:39 UTC, volkov-a-dev commented on src/header/Header.jsx
It's better to create a folder for the **Сomponents** and move the component headers there.
This folder will store those components that will be used on different pages.

2023-11-01 19:58 UTC, volkov-a-dev requested changes

2023-11-01 19:58 UTC, volkov-a-dev commented on src/index.js
> +import { BrowserRouter, BrowserRouter as Router } from "react-router-dom";
'Router' is declared but its value is never read.
'Router' is defined but never used.eslint[no-unused-vars](https://eslint.org/docs/latest/rules/no-unused-vars)

2023-11-01 19:58 UTC, volkov-a-dev commented on src/AppRouting.jsx
I'd rather put this in a separate folder: routing

2023-11-01 19:58 UTC, volkov-a-dev commented on src/components/header/Header.jsx
> +const routes = [
I would put this in constants or better yet in a config file. Where there were two objects, one contained the route constants. The second contained router data. Below is an example. I would also store everything in the routes folder
**routeConfig.js**
```
export const ROUTES_LIST = [
  {
          id: 1,
          name: 'home page',
          value: 'Home Page',
          path: '/',
  },
  {
          id: 2,
          name:  'examples',
          value: 'Examples',
          path: '/examples',
  }
   .....
```
```
export const routes = [
    {
        path:  ROUTES_LIST.path,
        component: HomePage,
        exact: true
    },
    {
        path: ROUTES_LIST.examples,
        component: Examples,
        exact: true
    },
    ....
]

```

2023-11-01 19:58 UTC, volkov-a-dev commented on src/components/header/Header.jsx
> +    <div>
Why is there a div here?

2023-11-01 19:58 UTC, volkov-a-dev commented on src/pages/examples/messenger/Chat.jsx
> +import "../../../style/chat.scss";
Everything that touches a component must be in the component's component. chat

2023-11-04 11:30 UTC, linhapeter commented
I have tried apply this logic in Examples.jsx  but EXAMPLES_ROUTES_LIST was always empty. Any idea what went wrong?
import { EXAMPLES_ROUTES_LIST } from "../../routing/config"

const renderedLinks = EXAMPLES_ROUTES_LIST?.map((route, id) => (
  <li key={id}>
    <Link to={route.path}>
      {route.value}
    </Link>
  </li>
));

const Examples = () => (
  <div>
    <ul>
      {renderedLinks}
    </ul>
    <Outlet />
  </div>
);

export default Examples;

2023-11-06 11:51 UTC, merged